# Generated by Django 5.0.2 on 2024-06-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='active',
            new_name='status',
        ),
    ]
